nodeLinker: node-modules

# packageExtensions:
#   "@vuepress/core@*":
#     dependencies:
#       escape-html: "*"
#   "@vuepress/markdown-loader@*":
#     dependencies:
#       "@vuepress/shared-utils": "*"
#   "@vuepress/shared-utils@*":
#     dependencies:
#       "@vue/component-compiler-utils": "*"
#       lru-cache: "*"
#       markdown-it-emoji: "*"
#   vuepress@*:
#     dependencies:
#       "@vuepress/shared-utils": "*"

yarnPath: .yarn/releases/yarn-berry.cjs
